/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DialoguesRouteImport } from './routes/dialogues'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryBlocksRouteImport } from './routes/library.blocks'
import { Route as LibraryFactionsRouteImport } from './routes/library.factions'
import { Route as LibraryGalaxyRouteImport } from './routes/library.galaxy'
import { Route as LibraryItemsRouteImport } from './routes/library.items'
import { Route as LibraryPlayfieldsRouteImport } from './routes/library.playfields'
import { Route as LibraryReputationRouteImport } from './routes/library.reputation'
import { Route as LibraryWarfareRouteImport } from './routes/library.warfare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DialoguesRoute = DialoguesRouteImport.update({
  id: '/dialogues',
  path: '/dialogues',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryBlocksRoute = LibraryBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryFactionsRoute = LibraryFactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryGalaxyRoute = LibraryGalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryItemsRoute = LibraryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryPlayfieldsRoute = LibraryPlayfieldsRouteImport.update({
  id: '/playfields',
  path: '/playfields',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryReputationRoute = LibraryReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryWarfareRoute = LibraryWarfareRouteImport.update({
  id: '/warfare',
  path: '/warfare',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/dialogues': typeof DialoguesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRouteWithChildren
  '/library/blocks': typeof LibraryBlocksRoute
  '/library/factions': typeof LibraryFactionsRoute
  '/library/galaxy': typeof LibraryGalaxyRoute
  '/library/items': typeof LibraryItemsRoute
  '/library/playfields': typeof LibraryPlayfieldsRoute
  '/library/reputation': typeof LibraryReputationRoute
  '/library/warfare': typeof LibraryWarfareRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/dialogues': typeof DialoguesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/library/blocks': typeof LibraryBlocksRoute
  '/library/factions': typeof LibraryFactionsRoute
  '/library/galaxy': typeof LibraryGalaxyRoute
  '/library/items': typeof LibraryItemsRoute
  '/library/playfields': typeof LibraryPlayfieldsRoute
  '/library/reputation': typeof LibraryReputationRoute
  '/library/warfare': typeof LibraryWarfareRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/dialogues': typeof DialoguesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRouteWithChildren
  '/library/blocks': typeof LibraryBlocksRoute
  '/library/factions': typeof LibraryFactionsRoute
  '/library/galaxy': typeof LibraryGalaxyRoute
  '/library/items': typeof LibraryItemsRoute
  '/library/playfields': typeof LibraryPlayfieldsRoute
  '/library/reputation': typeof LibraryReputationRoute
  '/library/warfare': typeof LibraryWarfareRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/dialogues'
    | '/export'
    | '/import'
    | '/library'
    | '/library/blocks'
    | '/library/factions'
    | '/library/galaxy'
    | '/library/items'
    | '/library/playfields'
    | '/library/reputation'
    | '/library/warfare'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/dialogues'
    | '/export'
    | '/import'
    | '/library/blocks'
    | '/library/factions'
    | '/library/galaxy'
    | '/library/items'
    | '/library/playfields'
    | '/library/reputation'
    | '/library/warfare'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/dialogues'
    | '/export'
    | '/import'
    | '/library'
    | '/library/blocks'
    | '/library/factions'
    | '/library/galaxy'
    | '/library/items'
    | '/library/playfields'
    | '/library/reputation'
    | '/library/warfare'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  DialoguesRoute: typeof DialoguesRoute
  ExportRoute: typeof ExportRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogues': {
      id: '/dialogues'
      path: '/dialogues'
      fullPath: '/dialogues'
      preLoaderRoute: typeof DialoguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/blocks': {
      id: '/library/blocks'
      path: '/blocks'
      fullPath: '/library/blocks'
      preLoaderRoute: typeof LibraryBlocksRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/factions': {
      id: '/library/factions'
      path: '/factions'
      fullPath: '/library/factions'
      preLoaderRoute: typeof LibraryFactionsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/galaxy': {
      id: '/library/galaxy'
      path: '/galaxy'
      fullPath: '/library/galaxy'
      preLoaderRoute: typeof LibraryGalaxyRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/items': {
      id: '/library/items'
      path: '/items'
      fullPath: '/library/items'
      preLoaderRoute: typeof LibraryItemsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/playfields': {
      id: '/library/playfields'
      path: '/playfields'
      fullPath: '/library/playfields'
      preLoaderRoute: typeof LibraryPlayfieldsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/reputation': {
      id: '/library/reputation'
      path: '/reputation'
      fullPath: '/library/reputation'
      preLoaderRoute: typeof LibraryReputationRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/warfare': {
      id: '/library/warfare'
      path: '/warfare'
      fullPath: '/library/warfare'
      preLoaderRoute: typeof LibraryWarfareRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryBlocksRoute: typeof LibraryBlocksRoute
  LibraryFactionsRoute: typeof LibraryFactionsRoute
  LibraryGalaxyRoute: typeof LibraryGalaxyRoute
  LibraryItemsRoute: typeof LibraryItemsRoute
  LibraryPlayfieldsRoute: typeof LibraryPlayfieldsRoute
  LibraryReputationRoute: typeof LibraryReputationRoute
  LibraryWarfareRoute: typeof LibraryWarfareRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryBlocksRoute: LibraryBlocksRoute,
  LibraryFactionsRoute: LibraryFactionsRoute,
  LibraryGalaxyRoute: LibraryGalaxyRoute,
  LibraryItemsRoute: LibraryItemsRoute,
  LibraryPlayfieldsRoute: LibraryPlayfieldsRoute,
  LibraryReputationRoute: LibraryReputationRoute,
  LibraryWarfareRoute: LibraryWarfareRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  DialoguesRoute: DialoguesRoute,
  ExportRoute: ExportRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
